### ISSUE TITLE
Security issue at API frontend 

### ISSUE THREAD

**Issue by hrizal** [punneetmehta/wapi_rest#12]
if someone have number link to your API
it is very easy to retrieve any data on her whatsapp
maybe better you add salt-key for accessing API from frontend (wapi.xyz) ?
salt-key may send to user via whatsapp

**Comment by punneetmehta** [comment]
Token based authorization added.

**Comment by yurisa2** [comment]
> Token based authorization added.

Bearer token?

**Comment by punneetmehta** [comment]
Send Auth header in following format :-
"Authorization: authTokenReceivedWhileLogin"
