### ISSUE TITLE
LOGIN ERROR

### ISSUE THREAD

**Issue by gustiarma** [punneetmehta/wapi_rest#14]
i got this errror when tried to login

{
  "error": 1,
  "message": {
    "error": 1,
    "message": "RESTORE_SESSION_ERROR|restore session connection timed out",
    "type": "LOGIN_ERROR",
    "username": "628125336xxx"
  }
}

**Comment by punneetmehta** [comment]
Either your device is not connected to Internet or WhatsApp App is not able to access internet or you might have logged out WhatsApp web session from the Device.

Please Check your Device Internet Connection, and WhatsApp Internet Connectivity or incase you have logged out, login again.
