### ISSUE TITLE
An authorization header is required

### ISSUE THREAD

**Issue by yurisa2** [punneetmehta/wapi_rest#15]
Oh, hi.

First of all. What a great service...

Until yesterday it was all going ok, but now I get 
{
  "error": 1,
  "message": "An authorization header is required"
}

Tried the authToken as a auth header in some combinations (found in most REST APIs), but no luck.

Any recommendation?

**Comment by punneetmehta** [comment]
Send Auth header in following format :-
"Authorization: <authTokenReceivedWhileLogin>"

**Comment by yurisa2** [comment]
Thanks, worked in postman, will check in the application later.

Thanks for the lightning fast response..
