### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by gustiarma** [punneetmehta/wapi_rest#2]
can you give some explanation how to use webhooks?  i already set my webhook but auto reply is not working

**Comment by punneetmehta** [comment]
Share the webhook link, and share the piece of code you are using in webhook

**Comment by gustiarma** [comment]
here's the webhook link:  https://responderwa.gurindampay.co.id/index.php

code stil from the github, not edited.


can you explain me how to make auto responder with your code?

**Comment by gustiarma** [comment]
and i;ve tried to send text message,
but  response show me this:

{
    "error": 1,
    "message": "message sending responded with %!d(float64=400)"
}

**Comment by punneetmehta** [comment]
Share the curl request for sending message

**Comment by punneetmehta** [comment]
@gustiarma you need to un-comment the lines starting with $webhookHelper functions, according to your requirements

**Comment by gustiarma** [comment]
Curl request i copy and paste from your website
Username : 6281253363512
Sending to : 6282124972353


I've tried uncomment it but it send like the image



Do you have sample code for auto responder?


I will try again tomorrow.

Thank you very much

**Comment by punneetmehta** [comment]
Just Tested it for sending message with your username and to the number you are sending to.
Problem is you need to append @s.whatsapp.net with the Number.

**curl Request :-**
`curl -X POST "https://in.wapi.xyz/sendTextMessage" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"username\": \"YourUSERNAME\", \"jid\": \"RECIPIENT@s.whatsapp.net\", \"message\": \"SGVsbG8sIFdvcmxk\"}"`

For auto responder, I'll share a sample code soon.

**Comment by punneetmehta** [comment]
Refer : https://github.com/punneetmehta/wapi_rest/commit/06997b317bbb7eac85501f8e747367fcdb1156ac
for Sample Auto Responder ( echoBot ) webhook file

**Comment by gustiarma** [comment]
i already use the echo bot and update my webhook.
but still got no auto reply from the bot.

**Comment by punneetmehta** [comment]
Please put any of your Linked Device Online.
So that i can check.

EchoBot is working perfectly fine, with one of my Device.

**Comment by gustiarma** [comment]
my device is online
1. 6281253363512
2. 6281240440907

Webhook URL :  http://responderwa.gurindampay.co.id/index.php

**Comment by gustiarma** [comment]
its done, thanks
