### ISSUE TITLE
error after sendTextMessage

### ISSUE THREAD

**Issue by gustiarma** [punneetmehta/wapi_rest#4]
whatsapp app and whatsapp business wont start after i send sentTextMessage command using cUrl on my server.

i have to clear data and login again to use it.

**Comment by punneetmehta** [comment]
Make sure to include @s.whatsapp.net or @g.us in jid to sendMessages.
Else whatsapp will create a problem.

If you send the messages without that Put the device on no internet mode and remove that conversation
Then you can start sending message again

**Comment by gustiarma** [comment]
its work , thanks

**Comment by gustiarma** [comment]
There's problem with webhook

Sometime it not immediately active
Sometime it took a long time till it working fine
But when it got delay it will repeat all the incoming message when you
using echobot

**Comment by punneetmehta** [comment]
Seems weird, I'll re-check the webhook functionality soon
