### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by pentateu** [punneetmehta/wapi_rest#5]

**Comment by punneetmehta** [comment]
I am not sharing code, but offering the service for free.

Sharing the code will most probably lead to its misuse, for spamming or marketing purposes.

and We don't Entertain such behaviour

**Comment by pentateu** [comment]
:) .. you don't understand open source, do you? Anyway good luck.

**Comment by punneetmehta** [comment]
Maybe/Maybe not.

Anyway, let's just end the argument.
