### ISSUE TITLE
How Function ?

### ISSUE THREAD

**Issue by Theblood** [punneetmehta/wapi_rest#6]
Help me!

**Comment by punneetmehta** [comment]
Can you please be more specific?
You need help with what particular functionality?

**Comment by pablopolanco6** [comment]
I would like to know your email or whatsapp to talk better, about your api is great

**Comment by pablopolanco6** [comment]
if I close the whatsapp login window works perfect? is only to have internet on mobile, I can also connect all devices that I put on?

**Comment by punneetmehta** [comment]
Yes you need to scan the qr code once, then you can close the window.
Only thing that is required to use the RestAPI as expected is to make sure the device is connected to internet and whatsapp web session is not logged out from the device.

**Comment by pablopolanco6** [comment]
with this I can do a chatbot? @punneetmehta

**Comment by punneetmehta** [comment]
Yes, you need to set webhook for that.

Webhook example is available in github repo.
You can modify it for your custom needs

**Comment by pablopolanco6** [comment]
If I host the webhook on my server, will the system recognize it and can I do a chatbot?

**Comment by punneetmehta** [comment]
Yes, you need to set webhook with your Username, from https://wapi.xyz

**Comment by pablopolanco6** [comment]
Are you available for freelance? If you can, you can contact me at my email

**Comment by pablopolanco6** [comment]
Are you available for freelance? If you can, you can contact me at my email

pablopolanco64@gmail.com
