### ISSUE TITLE
Receive Message is not deliver to webhook

### ISSUE THREAD

**Issue by mex-web** [punneetmehta/wapi_rest#8]
My webhook url 👍 https://luck91.com/wapi/index.php

**Comment by mex-web** [comment]
Server only send web hook `"dataType":"online"`  not sending type ack or msg.
setting is set to 
```
{
  "error": 0,
  "settings": {
    "ackNotify": "YES",
    "msgNotify": "YES",
    "webhookURL": "http://luck91.com/wapi/index.php"
  }
}
```

**Comment by punneetmehta** [comment]
Webhook Functionality is working properly. Please Check again, at your end.
