### ISSUE TITLE
Message already received to user but shows error in api

### ISSUE THREAD

**Issue by mex-web** [punneetmehta/wapi_rest#9]
POST https://in.wapi.xyz/sendTextMessage
`{
  "username": "91*******927",
  "jid": "91*********5@s.whatsapp.net",
  "message": "SGVsbG8sIFdvcmxk"
}`

Response : `{"error":1,"message":"sending message timed out","messageId":"1BA2EB782EBF29192BC7","status":-1} `

**Comment by punneetmehta** [comment]
Message Timed Error is more like, message is queued for sending, but is not successfully sent in the defined timeout time.
